/*
 * Copyright (c) Yurii Yevdokimov
 * Released under the CC BY-NC-SA 4.0
 */
//auth
export const SIGNUP="SIGNUP"

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN="LOGIN"
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT="LOGOUT"
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';



//requests
export const REQUEST_LOADING="REQUEST_LOADING"
export const REQUEST_FAILED="REQUEST_FAILES"
export const SET_REQUEST="SET_REQUEST"

export const REQUESTS_LOADING="USER_REQUESTS_LOADING"
export const REQUESTS_FAILED="USER_REQUESTS_FAILED"
export const SET_REQUESTS="SET_USER_REQUESTS"




export const PLACE_REQUEST_LOADING="PLACE_REQUEST_LOADING"
export const PLACE_REQUEST_FAILED="PLACE_REQUEST_FAILED"
export const PLACE_REQUEST="PLACE_REQUEST"

export const CHANGE_REQUEST_LOADING="CHANGE_REQUEST_LOADING"
export const CHANGE_REQUEST_FAILED="CHANGE_REQUEST_FAILED"
export const CHANGE_REQUEST="CHANGE_REQUEST"

export const DELETE_REQUEST_LOADING="DELETE_REQUEST_LOADING"
export const DELETE_REQUEST_FAILED="DELETE_REQUEST_FAILED"
export const DELETE_REQUEST="DELETE_REQUEST"




//geo
export const GET_VOLUNTEERS_NEAR_ME_LOADING="GET_VOLUNTEERS_NEAR_ME_LOADING"
export const GET_VOLUNTEERS_NEAR_ME_FAILED="GET_VOLUNTEERS_NEAR_ME_FAILED"
export const SET_VOLUNTEERS_NEAR_ME="SET_VOLUNTEERS_NEAR_ME"

export const GET_REQUESTS_NEAR_ME_LOADING="GET_REQUESTS_NEAR_ME_LOADING"
export const GET_REQUESTS_NEAR_ME_FAILED="GET_REQUESTS_NEAR_ME_FAILED"
export const SET_REQUESTS_NEAR_ME="SET_REQUESTS_NEAR_ME"
export const SET_RECEIVER="SET_RECEIVER"




//admin
export const GET_ADMIN_USERS_LOADING="GET_ADMIN_USERS_LOADING"
export const GET_ADMIN_USERS_FAILED="GET_ADMIN_USERS_FAILED"
export const SET_ADMIN_USERS="SET_ADMIN_USERS"


export const GET_ADMIN_VOLUNTEERS_LOADING="GET_ADMIN_VOLUNTEERS_LOADING"
export const GET_ADMIN_VOLUNTEERS_FAILED="GET_ADMIN_VOLUNTEERS_FAILED"
export const SET_ADMIN_VOLUNTEERS="SET_ADMIN_VOLUNTEERS"


export const GET_ADMIN_REQUESTS_LOADING="GET_ADMIN_REQUESTS_LOADING"
export const GET_ADMIN_REQUESTS_FAILED="GET_REQUESTS_FAILED"
export const SET_ADMIN_REQUESTS="SET_ADMIN_REQUESTS"

